### PR TITLE
Clone live db locally

### PR DESCRIPTION
**Pull request by shankardevy**

### CODE REVIEW

**Comment by shankardevy** [comment]
I will leave it open for sometime to allow comments and revisions before merging.

**Comment by shankardevy** [comment]
one improvement that I look forward is to move all the variables to a .env style file and export it from there during the script execution. This would help having the script file clean.

**Comment by mosic** [comment]
Good work @shankardevy :+1:

**Comment by mosic** [comment]
Superseded by https://github.com/evercam/evercam-api/pull/457, closing.

**Pull request closed without merging**
