### PR TITLE
Update models api

### PR DESCRIPTION
**Pull request by shakeelanjum**
@mosic: Please review my changes w.r.t. updates in API and docs to represent extra fields in vendor_models table

### CODE REVIEW

**Comment by mosic** [comment]
@shakeelanjum Looks good but two tests are failing, fix them and you're free to merge.

**Comment by shakeelanjum** [comment]
@mosic: May I go for git push production master?

**Comment by mosic** [comment]
@shakeelanjum The tests are still failing, you should have fixed them before merging. Please fix them before deploying to production.

**Comment by shakeelanjum** [comment]
@mosic <https://github.com/mosic>: There were *0* hound errors, as I had
checked before merging and then I deployed.

**Comment by mosic** [comment]
@shakeelanjum I'm talking about Travis tests: https://travis-ci.org/evercam/evercam-api/builds/69707438

**Comment by marcoherbst** [comment]
I suspect Milos is talking about Travis.

I think this has been broken for some time ... ( we had it working a few
weeks ago after Vasily, but it must have broken shortly afterwards )

so, this isn't quite Shakeel's problem, but if Shakeel can fix it, then
excellent.

Shakeel - ?

m


On 6 July 2015 at 12:17, M. Shakeel Anjum <notifications@github.com> wrote:

> @mosic <https://github.com/mosic>: There were *0* hound errors, as I had
> checked before merging and then I deployed.
>
> On 6 July 2015 at 15:41, Miloš Mošić <notifications@github.com> wrote:
>
> > @shakeelanjum <https://github.com/shakeelanjum> The tests are still
> > failing, you should have fixed them before merging. Please fix them
> before
> > deploying to production.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/evercam/evercam-api/pull/365#issuecomment-118805843
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/pull/365#issuecomment-118822433>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@marcoherbst The tests were passing until before the merge: https://travis-ci.org/evercam/evercam-api/builds

This pull request broke the tests.

**Comment by marcoherbst** [comment]
Sorry. Ok, excellent. Tks.

I mistook it for https://travis-ci.org/evercam/evercam-dashboard/builds

M

On 6 July 2015 at 12:21, Miloš Mošić <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> The tests were passing
> until before the merge: https://travis-ci.org/evercam/evercam-api/builds
>
> This pull request broke the tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/pull/365#issuecomment-118823416>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by shakeelanjum** [comment]
Ok, looking into that.

**Pull request merged**
