### PR TITLE
Added migrate file to remove is_admin field from users table

### PR DESCRIPTION
**Pull request by azharmalik3**
@mosic

### CODE REVIEW

**Comment by mosic** [comment]
@azharmalik3 You need to add methods for both changes up and down, so the migration can be rolled back.

This is an example of such migration: https://github.com/evercam/evercam-api/blob/master/migrations/20150624150500_add_message_in_camera_share_requests.rb

**Comment by azharmalik3** [comment]
@mosic i am confused, why we add up and down? 
I want to remove `is_admin` field only from `users` table.

**Comment by mosic** [comment]
@azharmalik3 We need down migration in order to perform a migration rollback, it's very useful in development. This is a good resource for migrations in general: [Active Record Migrations — Ruby on Rails Guides](http://edgeguides.rubyonrails.org/active_record_migrations.html)

Using a change migration isn't enough here as you get this error when doing `bundle exec rake db:rollback`:

```
Sequel::Error: irreversible migration method used, you may need to write your own down method
```

Btw if you take a look at the example migration I provided you can see that you wrote it, so this shouldn't be a problem :wink:

**Comment by azharmalik3** [comment]
@mosic ok `add_column` in up and `remove_column` in down method. Right?

**Comment by mosic** [comment]
@azharmalik3 Actually the other way around, you want to remove `is_admin` column on up (when running `bundle exec rake db:migrate`) and add it on down (when running `bundle exec rake db:rollback`).

**Pull request merged**
