### PR TITLE
Remove live snapshot endpoint

### PR DESCRIPTION
**Pull request by fteem**
@mosic this removes the endpoint (after the rest is working/merged).

### CODE REVIEW

**Comment by liutingdu** [comment]
Why are we removing that endpoint? I am using it in the Android app for JPG cameras. Or am I misunderstanding something?

**Comment by fteem** [comment]
Hi Liuting,

No worries, this wont get merged in soon. I just created the PR for the
future  (maybe too early) for when we have migrated all clients to -media.

We are moving the endpoint over to -media (and making it compatible with
this one) so when the time is right the transition should be easy.

**Comment by liutingdu** [comment]
@fteem Good to know :) Do I need to make any change after that? Just let me know ~

**Comment by fteem** [comment]
Well the idea is the only change to be swapping the urls. I hope we pull
that out :)

**Comment by mosic** [comment]
@liutingdu Just to confirm, we will remove the endpoint only after the Android app and other clients start using the equivalent media.evercam.io endpoint. You will be the first to know when that happens :)

**Comment by liutingdu** [comment]
@mosic @fteem Thanks!

**Comment by mosic** [comment]
Instead of removing the endpoint I set it to redirect requests exactly as they're received to evercam-media. Closing this.

**Pull request closed without merging**
