### PR TITLE
eugenehp motion detection first

### PR DESCRIPTION
**Pull request by eugenehp**
work in progress

### CODE REVIEW

**Comment by eugenehp** [comment]
@mosic @marcoherbst hey folks, this one is ready to be merged. :+1:

**Comment by marcoherbst** [comment]
woohoooo !!!

On 16 August 2015 at 12:41, Eugene HP <notifications@github.com> wrote:

> @mosic <https://github.com/mosic> @marcoherbst
> <https://github.com/marcoherbst> hey folks, this one is ready to be
> merged. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/pull/405#issuecomment-131530607>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@eugenehp Thanks. Did the migration that creates the "remembrance" camera create some issues?

This is good to merge, just revert the `migrations/20160729.sql` file as it's all just whitespace changes.

**Comment by eugenehp** [comment]
@mosic thanks man, just reverted it. let me know if it works for you. :+1:

**Comment by eugenehp** [comment]
@mosic @marcoherbst 
> Did the migration that creates the "remembrance" camera create some issues?

It should be placed in the `Rakefile` using db migrations, but not in the schema files. I spent some time figuring out why do I have unknown camera, until I found it there. So let's keep the initial test cameras in the `Rakefile` and migrations will be strictly schema updates and nothing else.

Makes sense?

**Comment by mosic** [comment]
@eugenehp Yep, that's exactly how it should be. Thanks.

**Pull request merged**
