### PR TITLE
Add extra data

### PR DESCRIPTION
**Pull request by shakeelanjum**
@mosic, please review the code changes as tested locally, including:

1. migrations to add extra columns (separate for each attribute in vendor_models)
2. import data from csv file and put it in separate columns
3. split existing data in config and images groups into their separate columns

### CODE REVIEW

**Comment by mosic** [comment]
@shakeelanjum `import_vendor_models` rake task is failing for me (if I understood correctly, it's because I haven't provided an argument to it). What should I run to test your work?

This is what I've tried:

```
➜  api git:(add_extra_data) bundle exec rake import_vendor_models
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ruby    12136 jack    7u  IPv4 170029      0t0  TCP *:10453 (LISTEN)
 CSV file found

 Importing models_data_all.csv... 
 'models_data.csv' imported from AWS S3 

 Reading data from 'models_data_all.csv' for  
rake aborted!
TypeError: no implicit conversion of nil into String
/home/jack/evercam/api/Rakefile:105:in `+'
/home/jack/evercam/api/Rakefile:105:in `block (2 levels) in <top (required)>'
/home/jack/evercam/api/Rakefile:102:in `open'
/home/jack/evercam/api/Rakefile:102:in `block in <top (required)>'
/home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => import_vendor_models
```

**Comment by shakeelanjum** [comment]
@mosic, It requires a vendor id among: "evercam", "sercomm", "starvedia", "geniv", "tenvis", "sricam" (its limited for testing, after that I will update .csv file on S3 that will contain max data of vendors). We know that script will update any vendor_models which belong to the given vendor.

api git:(add_extra_data) bundle exec rake import_vendor_models["evercam"]

**Comment by mosic** [comment]
Okay, it seems to be running fine for "evercam" after running `import_vendor_data["evercam"]` first, but when I try other vendors it raises an error.

Here is what I got when I ran `bundle exec rake import_vendor_models["tenvis"]`:

```
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type boolean: ""
LINE 1: ...= '', "audio_url" = '', "more_info" = '', "poe" = '', "wifi"...
                                                             ^
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `async_exec'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `block in execute_query'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/logging.rb:33:in `log_yield'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `execute_query'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:167:in `block in execute'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:143:in `check_disconnect_errors'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:167:in `execute'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:512:in `_execute'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `block (2 levels) in execute'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:533:in `check_database_errors'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `block in execute'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/connection_pool/threaded.rb:99:in `hold'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `synchronize'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `execute'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/query.rb:50:in `execute_dui'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:932:in `execute_dui'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:778:in `update'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1973:in `_update_without_checking'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1960:in `_update'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1954:in `_update_columns'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1902:in `block (2 levels) in _save'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1124:in `around_update'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1886:in `block in _save'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1124:in `around_save'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1869:in `_save'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1549:in `block (2 levels) in save'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:2032:in `block in checked_transaction'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:134:in `_transaction'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:108:in `block in transaction'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `synchronize'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:97:in `transaction'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:2032:in `checked_transaction'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1549:in `block in save'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:2020:in `checked_save_failure'
/home/jack/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1549:in `save'
/home/jack/evercam/api/Rakefile:189:in `block in <top (required)>'
/home/jack/evercam/api/Rakefile:138:in `block (3 levels) in <top (required)>'
/home/jack/evercam/api/Rakefile:109:in `each'
/home/jack/evercam/api/Rakefile:109:in `block (2 levels) in <top (required)>'
/home/jack/evercam/api/Rakefile:102:in `open'
/home/jack/evercam/api/Rakefile:102:in `block in <top (required)>'
/home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/jack/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => specs_model
(See full trace by running task with --trace)
```

**Comment by mosic** [comment]
@shakeelanjum Ok, that issue is now fixed and the importing seems to go without problems.

Btw I noticed that some of the example vendors don't exist though ("geniv" and "evercam" - but there is "evercam-capture"), do you use a task for importing Vendors too?

**Comment by mosic** [comment]
@shakeelanjum Ok, that looks good. The next step is to add the rest of the data? I'd suggest trying to import everything locally and then we can deploy this.

**Pull request merged**
