### PR TITLE
Fixing travis build errors

### PR DESCRIPTION
**Pull request by shakeelanjum**
@mosic: Fixed error in mismatch of Model rspec and presenter attributes

### CODE REVIEW

**Comment by mosic** [comment]
@shakeelanjum It seems that the tests are still failing. Just to remind you, you can also run tests locally first with the comand `bundle exec rspec`

**Comment by shakeelanjum** [comment]
@mosic: 'bundle exec rspec' errors out like this:
...
2.ec2.garantiadata.com:16589 failed (count: 0) Timeout::Error: IO timeout
FI, [2015-07-07T15:09:56.171728 #4343]  INFO -- : Dalli/SASL authenticating as memcached-app19401891
I, [2015-07-07T15:09:56.670059 #4343]  INFO -- : Dalli/SASL: Authenticated
.....I, [2015-07-07T15:09:59.263181 #4343]  INFO -- : pub-memcache-16589.eu-west-1-1.2.ec2.garantiadata.com:16589 failed (count: 0) Timeout::Error: IO timeout
FI, [2015-07-07T15:09:59.594548 #4343]  INFO -- : Dalli/SASL authenticating as memcached-app19401891
I, [2015-07-07T15:10:00.096961 #4343]  INFO -- : Dalli/SASL: Authenticated
.I, [2015-07-07T15:10:01.193513 #4343]  INFO -- : pub-memcache-16589.eu-west-1-1.2.ec2.garantiadata.com:16589 failed (count: 0) Timeout::Error: IO timeout
FI, [2015-07-07T15:10:01.539003 #4343]  INFO -- : Dalli/SASL authenticating as memcached-app19401891
I, [2015-07-07T15:10:02.067559 #4343]  INFO -- : Dalli/SASL: Authenticated
..I, [2015-07-07T15:10:03.556183 #4343]  INFO -- : pub-memcache-16589.eu-west-1-1.2.ec2.garantiadata.com:16589 failed (count: 0) Timeout::Error: IO timeout
FI, [2015-07-07T15:10:03.890530 #4343]  INFO -- : Dalli/SASL authenticating as memcached-app19401891
I, [2015-07-07T15:10:04.414130 #4343]  INFO -- : Dalli/SASL: Authenticated
...

**Comment by mosic** [comment]
@shakeelanjum That's strange, I'll catch you on Skype to solve that.

**Comment by mosic** [comment]
Fixed in #386

**Pull request closed without merging**
