### PR TITLE
Added total_models to vendor_presenter

### PR DESCRIPTION
**Pull request by shakeelanjum**
@mosic: Please review

### CODE REVIEW

**Comment by mosic** [comment]
Looks good. Just update according to Hound's comments and it's good to merge.

**Comment by shakeelanjum** [comment]
@mosic: Can I deploy to production now?

**Comment by mosic** [comment]
Yup.

On 12 June 2015 at 15:16, M. Shakeel Anjum <notifications@github.com> wrote:

> @mosic <https://github.com/mosic>: Can I deploy to production now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/pull/349#issuecomment-111488901>.
>



-- 
Miloš Mošić
Lead Developer
Evercam.io
Skype: mosicmilos

**Comment by shakeelanjum** [comment]
I am getting "don't have access rights" error while pushing to production,
may be I am not allowed to.

Azhar tried to do that but he is failing because git says that head needs
to be fast forwarded, some changes are not available locally.

Regards.

**Comment by mosic** [comment]
I deployed just now, but ping me on Skype to discuss the deploy rights.

**Pull request merged**
