### PR TITLE
remove camera/test endpoint

### PR DESCRIPTION
**Pull request by fteem**

### CODE REVIEW

**Comment by mosic** [comment]
Looks good :+1: Just a reminder, you need to sign the CLA: https://www.clahub.com/agreements/evercam/evercam-api

**Comment by fteem** [comment]
I thought I had it signed. Will fix that. I forgot to check if any tests
need to be removed, will check/fix and merge.

**Comment by fteem** [comment]
@mosic I signed the CLA and removed the endpoint specs as well.

**Comment by mosic** [comment]
:+1:

**Pull request merged**
