### PR TITLE
Fixed travis tests for #380

### PR DESCRIPTION
**Pull request by eugenehp**
* tests fixed
* travis config fixed
* migration schemes fixed

### CODE REVIEW

**Comment by eugenehp** [comment]
good morning @mosic @marcoherbst
this is ready to be merged

**Comment by marcoherbst** [comment]
Lovely.

re: "

   - added THREESCALE_PROVIDER_KEY to TravisCI config #380" ... just FYI,
   we no longer use 3Scale.

Milos will merge this hopefully.

M

On 30 July 2015 at 07:02, Eugene HP <notifications@github.com> wrote:

> good morning @mosic <https://github.com/mosic> @marcoherbst
> <https://github.com/marcoherbst>
> this is ready to be merged
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/pull/386#issuecomment-126195841>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by eugenehp** [comment]
Great.

@marcoherbst it was a dependency on some of the processes, I'll remove it in the next batch then.

**Comment by mosic** [comment]
Good work @eugenehp :+1: 

Keeping 3Scale key for now is okay, we need to remove related code from both evercam-api and evercam-misc before we can remove the key. (I just created issues for both: https://github.com/evercam/evercam-api/issues/388, https://github.com/evercam/evercam-misc/issues/4)

Btw why did you change `pending` tests to `skipped`, did some of them pass?

**Comment by eugenehp** [comment]
@mosic good to know. thanks.

marked skipped, because it was no harm to do so. if you want we can change it back, however it's a syntax update, so I gave it a try.

**Comment by mosic** [comment]
@eugenehp No need, just wondering. Thanks.

**Comment by eugenehp** [comment]
good work, thanks @mosic

**Comment by eugenehp** [comment]
+1

**Pull request merged**
